[project]
name = "scaling-sentemb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dill>=0.4.0",
    "gradio>=5.49.1",
    "pandas>=2.3.3",
    "peft>=0.17.1",
    "prettytable>=3.16.0",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.3",
    "setuptools>=80.9.0",
    "torch==2.7.1",
    "transformers==4.54.1",
]
